# site properties and page defaults
title: Pediatric Musculoskeletal Imaging Lab
subtitle: University of Calgary
description: We use advanced and multimodal imaging to understand how growing bones develop, adapt, and stay healthy.
url: https://pediatricmsklab.ca
baseurl: ""
header: images/hero-placeholder.svg
footer: images/hero-placeholder.svg
proofer: false
logo: images/lab-logo-bear.png
logo-text: false

# site social media and other links
links:
  email: pediatricmsk@ucalgary.ca
  google-scholar: https://scholar.google.com/citations?hl=en&user=MKDRadIAAAAJ
  pubmed: https://pubmed.ncbi.nlm.nih.gov/?term=Whittier+DE
  profile: https://profiles.ucalgary.ca/danielle-whittier

### jekyll settings

# front matter defaults
defaults:
  # all markdown files
  - scope:
      path: ""
    values:
      layout: default
  # markdown files in /_members
  - scope:
      type: "members"
    values:
      layout: member
  # markdown files in /_posts
  - scope:
      type: "posts"
    values:
      layout: post

collections:
  # generate page for each member
  members:
    output: true
  # generate page for each post
  posts:
    output: true

# jekyll plugins
plugins:
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-feed

# code block syntax highlighting
highlighter: rouge

# jekyll theme
theme: null

# sass settings
sass:
  sass_dir: _styles

# force jekyll to include certain files/folders
include:
  - _styles
  - _scripts

# force jekyll to exclude certain files/folders
exclude:
  - README.md
  - LICENSE.md
  - CITATION.cff
